# Generated by Django 3.0.7 on 2020-08-02 07:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='コンクールCDかその他のCDか')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='曲名')),
                ('composer', models.CharField(max_length=200)),
                ('arranger', models.CharField(blank=True, max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('cd', models.CharField(blank=True, max_length=200)),
                ('cd_link', models.URLField(max_length=500)),
                ('cdYear', models.CharField(blank=True, max_length=4)),
                ('cdVol', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('asin', models.CharField(blank=True, max_length=10)),
                ('cd_type', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.PROTECT, to='app_music_db.CdType', verbose_name='CDタイプ')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無し', max_length=32, verbose_name='おなまえ')),
                ('text', models.TextField(verbose_name='ひとこと感想')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='コメント投稿日時')),
                ('song', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_music_db.Song', verbose_name='該当曲')),
            ],
        ),
    ]
