# Generated by Django 3.0.7 on 2020-08-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_music_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cd_link',
            field=models.CharField(max_length=500),
        ),
    ]
