# Generated by Django 3.0.7 on 2020-08-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_music_db', '0003_auto_20200807_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cdYear',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
