# Generated by Django 3.0.7 on 2020-08-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_music_db', '0004_auto_20200807_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('song',)},
        ),
    ]
