# Generated by Django 3.0.7 on 2020-08-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_music_db', '0005_auto_20200812_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
