# Generated by Django 3.0.7 on 2020-08-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_music_db', '0006_auto_20200812_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
